export declare enum EHistoryType {
    USE = "USE",
    MANUAL = "MANUAL",
    REVERT = "REVERT",
    CREDIT = "CREDIT",
    CREDIT_CHANGED_SETTING_MAX_ENTITLEMENT = "CREDIT_CHANGED_SETTING_MAX_ENTITLEMENT`",
    CREDIT_CHANGED_SETTING_PRORATE_TO_MAX = "CREDIT_CHANGED_SETTING_PRORATE_TO_MAX",
    CREDIT_PRORATE = "CREDIT_PRORATE",
    CREDIT_PRORATE_CHANGED_SETTING_PRORATE_UNIT = "CREDIT_PRORATE_CHANGED_SETTING_PRORATE_UNIT",
    CREDIT_PRORATE_CHANGED_SETTING_MAX_TO_PRORATE = "CREDIT_PRORATE_CHANGED_SETTING_MAX_TO_PRORATE",
    CARRY_FORWARD = "CARRY_FORWARD",
    CARRY_FORWARD_EXPIRES = "CARRY_FORWARD_EXPIRES",
    RENEWAL_YEARLY = "RENEWAL_YEARLY",
    DEDUCT_CREDIT = "DEDUCT_CREDIT",
    DEDUCT_CARRY_FORWARD = "DEDUCT_CARRY_FORWARD",
    REVERT_DEDUCT_CREDIT = "REVERT_DEDUCT_CREDIT",
    REVERT_DEDUCT_CARRY_FORWARD = "REVERT_DEDUCT_CARRY_FORWARD",
    IMPORT = "IMPORT"
}
