export declare enum DocumentActionLanguageCode {
    Arabic = "ar",
    ChineseSimplified = "zh",
    ChineseTraditional = "zh_TW",
    Czech = "cs",
    Danish = "da",
    Dutch = "nl",
    English = "en",
    French = "fr",
    German = "de",
    Hebrew = "he",
    Hungarian = "hu",
    Indonesian = "id",
    Italian = "it",
    Japanese = "ja",
    Polish = "pl",
    Portuguese = "pt",
    Russian = "ru",
    Slovak = "sk",
    Spanish = "es",
    Swedish = "sv",
    Thai = "th",
    Vietnamese = "vi"
}
